services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=gouser
      - DB_PASSWORD=gopassword
      - DB_NAME=godb
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - app-network
    # アプリが終了しないように設定
    command: ["sleep", "infinity"]

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=godb
      - MYSQL_USER=gouser
      - MYSQL_PASSWORD=gopassword
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init-db:/docker-entrypoint-initdb.d
    restart: unless-stopped
    networks:
      - app-network
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql-data:

networks:
  app-network:
    driver: bridge